Stage3
pograncheg/fw_creation pull request #2
Opened 2024-08-05 11:13 UTC by pograncheg

Задания 3-го этапа.

2024-08-05 11:48 UTC, pnkrtp requested changes

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
> +        echo '<br>';
никаких выводов в ядре

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
> +        $obj->template->includeTemplate($obj->params, $obj->result);
шаблон должен подключать сам компонент, а не наш основной класс. Это не его работа.

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
> +        $obj->template->__relativePath = 'localhost/' . $obj->template->__path;
Никаких локалхостов

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
> +        include $componentPath . '/' . $componentId . '/.class.php';
Необходимо сохранять результат найденного класса нужного компонента, иначе 2 комопнента на странице приведут к ошибке.

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
> +        $this->pager->addCss('Fw/assets/main.css');
убрать отсюда любые добавления ассетов. Им тут не место.

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
>          $this->pager->setProperty('title', 'MySite');
Убрать из основного класса добавление свойств. Им тут не место.

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Component/Template.php
> +    public function __construct(string $id, $component)
Нет связи с объектом компонента

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Component/Template.php
> +    public function includeTemplate($params, $result)
$param и $result - это результат работы компонента, он не должен поступать из вне, он должен браться из нашего родительского компонента.
Шаблон компонента - не может существовать без самого компонента

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/Core/Page.php
> +            foreach ($this->head['js'] as $el) {
Зачем циклом проходить, если можно просто implode сделать элементов, просто в массив должны добавляться сразу правильные строки.

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/components/fw/interface.form/.class.php
> +    }
вот тут бы подключить шаблон)

2024-08-05 11:48 UTC, pnkrtp commented on htdocs/Fw/init.php
> +spl_autoload_register(function ($class) {
в теории, можно регламентировать неймспейсы компонентов исходя из названия и создать доп загрузчик для компонентов, но это в теории)

2024-08-05 12:06 UTC, pograncheg commented on htdocs/Fw/Core/Application.php
> +        echo '<br>';
Тестировал вывод и забыл почистить. Виноват.

2024-08-05 12:06 UTC, pograncheg commented on htdocs/Fw/Core/Application.php
> +        $obj->template->__relativePath = 'localhost/' . $obj->template->__path;
Меняем на $_SERVER['SERVER_NAME'].

2024-08-05 12:07 UTC, pograncheg commented on htdocs/Fw/Core/Application.php
> +        $this->pager->addCss('Fw/assets/main.css');
Тестировал работу с макросами и буфером во 2-ом этапе.

2024-08-05 12:32 UTC, pograncheg commented on htdocs/Fw/Core/Page.php
> +            foreach ($this->head['js'] as $el) {
Поправил.

2024-08-06 14:19 UTC, pnkrtp requested changes

2024-08-06 14:19 UTC, pnkrtp commented on htdocs/Fw/Core/Application.php
> +        $obj->template = new \Fw\Core\Component\Template($template, $obj);
убрать в базовый класс компонента

2024-08-06 14:19 UTC, pnkrtp commented on htdocs/Fw/Core/Component/Template.php
> +            \Fw\Core\InstanceContainer::getInstance(\Fw\Core\Page::class)->addCss($this->__path . 'style.css');
убрать неймспейсы в use

2024-08-06 17:17 UTC, merged